name: check
on:
  pull_request:
  push:
    branches: [master]
jobs:
  episodes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 scripts/check-episodes.py
